apiVersion: apps/v1
kind: Deployment
metadata:
  name: leah-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leah-api
  template:
    metadata:
      labels:
        app: leah-api
    spec:
      containers:
        - name: leah-api
          image: us-west3-docker.pkg.dev/api-tests-391115/leah-api
          ports: 
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10